### ISSUE TITLE
Issue in installing!

### ISSUE THREAD

**Issue by ajay-yug** [pshirishreddy/hand_mouse#1]
g++ -lX11 `pkg-config opencv --cflags --libs` HandGesture.cpp -o main.o
In file included from HandGesture.cpp:13:0:
mouse.h: In function ‘void mouseClick(int)’:
mouse.h:84:15: error: ‘usleep’ was not declared in this scope
  usleep(100000);
               ^
make: **\* [main.o] Error 1

**Comment by pshirishreddy** [comment]
Thanks for reporting issue, I am no longer maintaining this project.
